language: generic
sudo: required

services:
  - docker

env:
  - IMAGE=core-api
  - IMAGE=core-stretch
  - IMAGE=buildenv-stretch
  - IMAGE=buildenv-trusty
  - IMAGE=w2d

before_script:
  - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}

script:
  - make ${IMAGE}
  - make publish-${IMAGE}

notifications:
  webhooks:
    urls:
      - http://188.166.87.141:9090/v1/travis
    on_start: always
